/**
 * Narrative Databank
 *
 * Provides access to the collection of validated scenes generated by live CI tests.
 * The databank is populated by generateLiveScenes.test.js when scenes pass validation.
 *
 * Usage:
 *   import { getNarrativeBankScenes, getNarrativeBankSize } from '$lib/server/ai/narrativeBank';
 *   const scenes = getNarrativeBankScenes();
 *   const size = getNarrativeBankSize();
 */

import type { Scene } from '$lib/contracts';

interface BankedScene {
	timestamp: number;
	contextId: string;
	contextDescription: string;
	scene: Scene;
	sanityResult: {
		ok: boolean;
		blockingIssues: string[];
		retryableIssues: string[];
	};
}

interface NarrativeBank {
	scenes: BankedScene[];
	updatedAt: string | null;
	description?: string;
}

let cachedBank: NarrativeBank | null = null;

/**
 * Load the narrative databank (cached after first load)
 */
export function getNarrativeBank(): NarrativeBank {
	if (cachedBank) {
		return cachedBank;
	}

	try {
		// This will be bundled at build time and available in the browser
		const data = require('$lib/data/narrativeBank.json') as NarrativeBank;
		cachedBank = data;
		return data;
	} catch (error) {
		console.warn('Failed to load narrative databank:', error);
		return { scenes: [], updatedAt: null };
	}
}

/**
 * Get all banked scenes
 */
export function getNarrativeBankScenes(): BankedScene[] {
	const bank = getNarrativeBank();
	return bank.scenes || [];
}

/**
 * Get the number of scenes in the databank
 */
export function getNarrativeBankSize(): number {
	return getNarrativeBankScenes().length;
}

/**
 * Get scenes filtered by context
 */
export function getNarrativeBankScenesByContext(contextId: string): BankedScene[] {
	return getNarrativeBankScenes().filter((s) => s.contextId === contextId);
}

/**
 * Get a random scene from the databank (or filtered by context)
 */
export function getRandomNarrativeBankScene(contextId?: string): BankedScene | null {
	const scenes = contextId
		? getNarrativeBankScenesByContext(contextId)
		: getNarrativeBankScenes();

	if (scenes.length === 0) {
		return null;
	}

	return scenes[Math.floor(Math.random() * scenes.length)];
}

/**
 * Get the last N scenes (most recent first)
 */
export function getRecentNarrativeBankScenes(count: number): BankedScene[] {
	const scenes = getNarrativeBankScenes();
	return scenes.slice(-count).reverse();
}

/**
 * Check if databank is populated
 */
export function isNarrativeBankPopulated(): boolean {
	return getNarrativeBankSize() > 0;
}

/**
 * Get last update timestamp
 */
export function getNarrativeBankLastUpdated(): string | null {
	return getNarrativeBank().updatedAt || null;
}
