/**
 * Narrative quality CI reporter.
 * Generates JSON and markdown artifacts.
 */
import fs from 'node:fs';
import path from 'node:path';

const ARTIFACTS_DIR = path.join(process.cwd(), 'artifacts');

function ensureArtifactsDir() {
	if (!fs.existsSync(ARTIFACTS_DIR)) {
		fs.mkdirSync(ARTIFACTS_DIR, { recursive: true });
	}
}

export function writeReport(report) {
	ensureArtifactsDir();

	const jsonPath = path.join(ARTIFACTS_DIR, 'narrative-quality-report.json');
	fs.writeFileSync(jsonPath, JSON.stringify(report, null, 2));

	const mdPath = path.join(ARTIFACTS_DIR, 'narrative-quality-summary.md');
	fs.writeFileSync(mdPath, formatMarkdown(report));

	return { jsonPath, mdPath };
}

function formatMarkdown(report) {
	const lines = [];
	lines.push('# Narrative Quality CI Report');
	lines.push('');
	lines.push(`**Date:** ${new Date().toISOString()}`);
	lines.push(`**Status:** ${report.passed ? 'PASS' : 'FAIL'}`);
	lines.push('');

	// Tier 1 summary
	lines.push('## Tier 1: Blocking Gates');
	lines.push('');
	lines.push('| Suite | Tests | Passed | Failed |');
	lines.push('|-------|-------|--------|--------|');
	for (const suite of report.tier1.suites) {
		const failCount = suite.total - suite.passed;
		const status = failCount === 0 ? 'ok' : 'FAIL';
		lines.push(`| ${suite.name} | ${suite.total} | ${suite.passed} | ${failCount} ${status !== 'ok' ? '**' + status + '**' : ''} |`);
	}
	lines.push('');
	lines.push(`**Tier 1 Total:** ${report.tier1.totalPassed}/${report.tier1.totalTests} passed`);
	lines.push('');

	// Tier 1 failures detail
	const allFailures = report.tier1.suites.flatMap((s) =>
		s.failures.map((f) => ({ suite: s.name, ...f }))
	);
	if (allFailures.length > 0) {
		lines.push('### Tier 1 Failures');
		lines.push('');
		for (const f of allFailures) {
			lines.push(`- **[${f.suite}]** ${f.test}: ${f.reason}`);
		}
		lines.push('');
	}

	// Tier 2 summary
	lines.push('## Tier 2: Narrative Quality Scores (Non-blocking)');
	lines.push('');

	if (report.tier2.fixtureScores.length > 0) {
		lines.push('### Fixture Scores');
		lines.push('');
		lines.push('| Fixture | Conventional | Unconventional | Overall |');
		lines.push('|---------|-------------|----------------|---------|');
		for (const fs of report.tier2.fixtureScores) {
			lines.push(`| ${fs.id} | ${fs.scores.summary.conventionalAvg}/5 | ${fs.scores.summary.unconventionalAvg}/5 | **${fs.scores.summary.overallAvg}/5** |`);
		}
		lines.push('');

		// Detailed breakdown for each fixture
		for (const fs of report.tier2.fixtureScores) {
			lines.push(`#### ${fs.id}`);
			lines.push('');
			lines.push('**Conventional:**');
			for (const [k, v] of Object.entries(fs.scores.conventional)) {
				lines.push(`- ${k}: ${v}/5`);
			}
			lines.push('');
			lines.push('**Unconventional:**');
			for (const [k, v] of Object.entries(fs.scores.unconventional)) {
				lines.push(`- ${k}: ${v}/5`);
			}
			lines.push('');
		}
	}

	// Baseline comparison
	if (report.tier2.baselineComparison) {
		const bc = report.tier2.baselineComparison;
		lines.push('### Baseline Comparison');
		lines.push('');
		lines.push(`- Baseline average: ${bc.baselineAvg}/5`);
		lines.push(`- Current average: ${bc.currentAvg}/5`);
		lines.push(`- Delta: ${bc.delta > 0 ? '+' : ''}${bc.delta}`);
		lines.push(`- Status: ${bc.regression ? '**REGRESSION WARNING**' : 'OK'}`);
		lines.push('');
	}

	lines.push('---');
	lines.push('*Generated by narrative-quality CI pipeline*');

	return lines.join('\n');
}
